name: Deploy Docs

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    tags:
      - v*
    branches:
      - vitepress-test

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - name: clone docs
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        path: docs-files

    - name: clone frontend
      uses: actions/checkout@v3
      with:
        repository: 'emqx/docs-emqx-com-frontend'
        ref: next
        token: ${{ secrets.CI_GIT_TOKEN }}
        path: frontend

    - name: use node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16

    - name: use pnpm
      uses: pnpm/action-setup@v2
      with:
          version: 8.5.1

    - name: use python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'

    - name: set env
      run: |
         BRANCH=$(echo ${{ github.ref }} | sed -r  "s ^refs/heads/|^refs/tags/(.*) \1 g")
         if [ "$BRANCH" = "vitepress-test" ];then
         VERSION="latest"
         else
         VERSION=$BRANCH
         fi
         echo "DOCS_BRANCH=$BRANCH" >> $GITHUB_ENV
         echo "VERSION=$VERSION" >> $GITHUB_ENV
         echo "DOCS_TYPE=xmeter-cloud" >> $GITHUB_ENV

    - name: remove unused files
      run: |
        cd docs-files
        python3 .github/scripts/remove_unused.py $(pwd)

    - name: move files
      run: |
        rm frontend/docs/en/index.md || true
        rm frontend/docs/zh/index.md || true
        rm frontend/docs/*.md || true
        rm frontend/index.md
        mkdir -p frontend/docs/en/${DOCS_TYPE}/${VERSION}/
        mkdir -p frontend/docs/zh/${DOCS_TYPE}/${VERSION}/
        mkdir -p frontend/docs/.vitepress/public/api/
        cp -r docs-files/en_US/* frontend/docs/en/${DOCS_TYPE}/${VERSION}/
        cp -r docs-files/zh_CN/* frontend/docs/zh/${DOCS_TYPE}/${VERSION}/
        cp docs-files/directory.json frontend/docs/.vitepress/config/directory.json

    - name: generate version config
      run: |
        cd docs-files
        python3 .github/scripts/generate_version.py $(git tag | egrep "v[0-9](\.[0-9])*$" | xargs echo -n) > ../frontend/docs/.vitepress/public/api/${DOCS_TYPE}_versions.json
        cat ../frontend/docs/.vitepress/public/api/${DOCS_TYPE}_versions.json

    - name: build docs
      run: |
        cd frontend
        yarn && yarn build

    - name: upload dist
      run: |
        pip3 install coscmd
        coscmd config -a ${{ secrets.TENCENT_COS_ID }} -s ${{ secrets.TENCENT_COS_KEY }} -b docs-preview-1302406139 -e cos.accelerate.myqcloud.com
        coscmd upload -r frontend/docs/.vitepress/dist/ /
